### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by SnorlaxYum** [SnorlaxYum/Simputer#1]
- [x] Move some notes posts to a new archive sub
- [x] Fixed some style on isso second-level that didn't look well on the phone
- [x] Reduce the js size

**Comment by SnorlaxYum** [comment]
This list is close to complete! Will commit once the files are production-ready

**Comment by SnorlaxYum** [comment]
Complete!
