### ISSUE TITLE
20191123 - To-do

### ISSUE THREAD

**Issue by SnorlaxYum** [SnorlaxYum/Simputer#2]
Currently something like things like slugify in the blog is so weird, so I could probably do this in the future:  

- [x] Output the slugs through json directly
- [x] ~~Then it should be really easy to do rss~~Switch to the atom feed as they are much more widely supported by modern browsers

**Comment by SnorlaxYum** [comment]
I've done both of them. Then I should be add the link to atom feed later. I've been wondering if I should do a feed for the whole site as well.

- [x] Do the feed for the whole site
- [x] Optimize the python code
- [x] Isso styling problem on nested edit area in mobile devices
